### ISSUE TITLE
Missing prerequisites in the docs

### ISSUE THREAD

**Issue by manuel-di-iorio** [arthurmassanes/flappy#2]
Please make it clear in the README.md that **cmake** is a prerequisite to install the npm dependencies and that **Node.js v12** is required to run the game.

npm install error: `Cmake is not installed. Install CMake` (Fix: https://cmake.org/download)
npm start error: `src\Game.js:25  restart = () => { SyntaxError: Unexpected token =` (Fix: use node>12)

**Comment by arthurmassanes** [comment]
My bad, added it to the README !
https://github.com/arthurmassanes/flappy/commit/984220bb2da386387f14dbdc68df4bd819cb725f
